receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318

processors:
  batch:

exporters:
  file/traces:
    path: __TRACE_OTEL_TRACES__
    format: json
  file/logs:
    path: __TRACE_OTEL_LOGS__
    format: json
  file/metrics:
    path: __TRACE_OTEL_METRICS__
    format: json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/traces]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/logs]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/metrics]
